server:
  servlet:
    encoding:
      force-response: true


spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 300MB
  config:
    activate:
      on-profile: "common"
    servelet:
      multipart:
        max-request-size: 400MB
        max-file-size: 400MB
  cloud:
    aws:
      region:
        static: ap-northeast-2
jwt:
  token:
    secret: "secreteKey"


#cloud:
#  aws:
#    credentials:
#      access-key: "aws-access-key"
#      secret-key: "aws-secret-key"
#
#    region:
#      static: "aws-region"
#
#    stack:
#      auto: false
